import { BRAND, budgetRows, team } from './resource-data.mjs';

export const slides = [
  { kind: 'cover', title: 'CCSF Crime Prevention Unit', subtitle: '' },
  { kind: 'cards', title: 'Mandate, purpose and operating boundaries', subtitle: 'A prevention unit that strengthens awareness, early reporting and structured referral without replacing CPS response authority.', cols: 2, cards: ['MANDATE\nPrevent avoidable harm through awareness, student engagement, digital reporting and reliable safety information.', 'POSITIONING\nA student-facing crime prevention unit operating under Campus Protection Services.', 'WHAT THE UNIT DOES\nAwareness, intake, triage support, documentation, communications, trend analysis and campus activations.', 'WHAT THE UNIT DOES NOT DO\nIt does not exercise police powers, conduct independent disciplinary hearings or replace official CPS command.'] },
  { kind: 'org', title: 'Corporate placement and functional structure', subtitle: 'Clear authority, advisory review and a disciplined internal operating model.' },
  { kind: 'team', title: 'Six-person functional allocation', subtitle: 'Positions are assigned to create accountability while maintaining cross-functional support.', people: team },
  { kind: 'flow', title: 'Case handling and referral workflow', subtitle: 'Every report moves through controlled stages with clear ownership and audit evidence.', items: ['Student submits', 'Intake validates', 'Risk is triaged', 'CPS / authorised office receives', 'Student receives update'], notes: ['Digital intake checks completeness, identity, campus, location and relevant evidence.', 'Serious risk is escalated immediately; lower-risk matters enter a documented referral pathway.', 'Investigation and disciplinary authority remains with the relevant authorised university or external body.', 'Administration maintains the reference, timeline, handover record and close-out evidence.'] },
  { kind: 'cards', title: 'Who handles what after intake', subtitle: 'The unit separates intake, referral, records, communication and quality control.', cols: 3, cardH: 1.55, fontSize: 9.5, cards: ['DIGITAL INTAKE\nObakeng Junior Msueti validates the report, reference, location and evidence.', 'RISK & OPERATIONS\nThipo Mapanga coordinates prevention action and immediate field referral where approved.', 'OFFICIAL INVESTIGATION\nCPS or the authorised university/external office conducts formal investigation.', 'RECORDS & COMPLIANCE\nPascal controls files, registers, minutes, consent and close-out records.', 'COMMUNICATION\nNjonvelo Mayule prepares approved student updates and awareness messaging.', 'QUALITY ASSURANCE\nHangani reviews patterns, data quality and improvement actions.'] },
  { kind: 'cards', title: 'Online scam and academic fraud reporting', subtitle: 'Use low-risk digital cases to demonstrate early-reporting value during the Pilot.', cols: 2, cards: ['REPORTABLE EXAMPLES\nCourse selling, fake registration access, mark-change offers, fraudulent academic records and staff impersonation.', 'STUDENT EVIDENCE\nScreenshots, usernames, phone numbers, URLs, payment requests, dates and transaction references.', 'SAFE ACTION\nDo not pay, threaten or confront the suspected offender. Report through the Pilot and preserve originals.', 'REFERRAL\nRoute to CPS and the relevant academic, ICT, legal, disciplinary or external authority as determined by official processes.'] },
  { kind: 'flow', title: 'App-based prevention and support pathway', subtitle: 'The app connects information, reporting, routing and student feedback.', items: ['QR / app access', 'Document library', 'Pilot report', 'Authorised routing', 'Status and review'], notes: ['Campus guides remain downloadable instead of being discarded after an activation.', 'The Pilot records usability and reporting tests separately from production cases.', 'Readable locations and case references improve handover quality.', 'Student feedback informs workflow, content and campus rollout improvements.'] },
  { kind: 'cards', title: 'Campus Guide & Document Library', subtitle: 'A permanent information centre inside the Pilot and future production app.', cols: 2, cards: ['CAMPUS NAVIGATION\nBuilding 1-60 register, departments, verified rooms and student-service routes.', 'SAFETY HANDBOOKS\nPrevention checklists, emergency routes, privacy, evidence and case tracking.', 'UNIT DOCUMENTS\nOperating structure, activation plans, approved procedures and training material.', 'VERSION CONTROL\nPublication date, version, file type, active status and managed replacement.'] },
  { kind: 'cards', title: 'Pretoria West Pilot activation model', subtitle: 'Start at home, measure the model and refine it before campus-to-campus expansion.', cols: 2, cards: ['WEDNESDAY ALERT DRIVE\nA visible weekly gazebo or help point for prevention advice, app demonstrations and student feedback.', 'SAFETY HELP DESKS\nHigh-traffic support points for safe-route reminders, emergency contacts and reporting guidance.', 'EVENT SUPPORT\nAwareness, code-of-conduct messaging, queue guidance and reporting routes without replacing guards.', 'RECRUITMENT & RECOGNITION\nBuild a disciplined student safety community through training, certificates and approved support.'] },
  { kind: 'flow', title: 'Campus-to-campus rollout', subtitle: 'Evidence and approval precede replication.', items: ['Pretoria West pilot', 'Measure & refine', 'Leadership approval', 'Campus activation trips', 'Institution-wide model'], notes: ['Use a standard activation pack, register, QR set, briefing and close-out report.', 'Coordinate every visit with local CPS and campus management.', 'Do not publish unverified campus building or emergency information.', 'Maintain one central performance dashboard and document repository.'] },
  { kind: 'table', title: 'Estimated financial framework', subtitle: 'Planning estimates only; all expenditure requires approval, procurement compliance and supporting evidence.', rows: budgetRows },
  { kind: 'cards', title: 'Financial controls and accountability', subtitle: 'A transparent activity-based model protects CPS, CCSF and the university.', cols: 2, cards: ['PRE-APPROVAL\nNo commitment is made before the activity, scope and estimate are approved.', 'ACTIVITY BUDGET\nEach trip or activation has its own transport, material, accommodation and contingency lines.', 'SUPPORTING RECORDS\nQuotes, approvals, attendance, invoices, proof of delivery and close-out evidence are filed.', 'RECONCILIATION\nActual spend is compared with the approved estimate and exceptions are explained.', 'SEPARATION OF DUTIES\nRequest, approval, purchasing, receipt and reconciliation should not rest with one person.', 'REPORTING\nMonthly summaries show approved, committed, spent and remaining amounts by activity.'] },
  { kind: 'cards', title: 'Communication and reporting lines', subtitle: 'Professional routing prevents duplication and protects authority.', cols: 2, cards: ['CPS DIRECTORATE\nReceives formal submissions, decisions, risk escalation and performance reports.', 'DESIGNATED REVIEW CHANNEL\nReviews drafts, corrections, readiness and compliance before formal submission where required.', 'INTERNAL UNIT\nUses one action register, documented decisions, named owners and deadlines.', 'EXTERNAL UNIVERSITY OFFICES\nCommunication is factual, authorised, need-to-know and linked to a reference.', 'STUDENTS\nMessages are clear, prevention-first, respectful and free of unverified allegations.', 'PUBLIC / PARTNERS\nOnly approved representatives issue statements or commitments.'] },
  { kind: 'cards', title: 'Governance, records and confidentiality', subtitle: 'Every action must be traceable and proportionate.', cols: 3, cardH: 1.55, fontSize: 9.5, cards: ['CASE REGISTER\nReference, category, campus, date, owner, status and referral.', 'HANDOVER RECORD\nWhat was sent, to whom, when and under which authority.', 'CONSENT & PRIVACY\nLimit data to the purpose and protect evidence access.', 'MEETING RECORDS\nDecisions, actions, owners, deadlines and approvals.', 'CONTENT CONTROL\nVersion, publisher, approval status and expiry/review date.', 'CLOSE-OUT\nOutcome, student update, lessons and archived evidence.'] },
  { kind: 'cards', title: 'Performance dashboard', subtitle: 'Measure prevention value, not only the number of reports.', cols: 3, cardH: 1.55, fontSize: 9.5, cards: ['AWARENESS REACH\nStudents engaged and campuses covered.', 'DIGITAL ADOPTION\nQR scans, document downloads and active Pilot users.', 'REPORT QUALITY\nComplete locations, relevant evidence and reduced duplicates.', 'ROUTING QUALITY\nTime to validate, refer and acknowledge.', 'PREVENTION OUTCOMES\nHazards resolved, scam alerts issued and recurring risks reduced.', 'TRUST & LEARNING\nRatings, feedback themes and implemented improvements.'] },
  { kind: 'cards', title: '90-day implementation plan', subtitle: 'Move from structure approval to an evidence-led campus pilot.', cols: 2, cards: ['DAYS 1-15\nConfirm structure, role allocation, review channel, registers, document library and approved Pilot scenarios.', 'DAYS 16-30\nTrain the six-person team, test digital intake, prepare scam-reporting messaging and activation material.', 'DAYS 31-60\nRun Pretoria West weekly activations, collect app feedback and process authorised low-risk Pilot cases.', 'DAYS 61-90\nEvaluate performance, reconcile costs, correct the model and submit the campus expansion proposal.'] },
  { kind: 'cards', title: 'Decision requests', subtitle: 'Leadership decisions required to operationalise the unit.', cols: 2, cards: ['APPROVE THE STRUCTURE\nConfirm the unit placement, reporting line and six functional portfolios.', 'APPROVE PILOT SCOPE\nConfirm authorised reporting scenarios, data handling and referral boundaries.', 'APPROVE ACTIVATION MODEL\nConfirm Pretoria West schedule, campus permissions and standard activation pack.', 'APPROVE FINANCIAL PROCESS\nConfirm estimates, procurement route, sign-off and reconciliation requirements.', 'APPROVE DOCUMENT LIBRARY\nConfirm publication, version control and update authority.', 'APPROVE SCALE GATE\nCampus expansion follows evidence, feedback, readiness and leadership approval.'] },
  { kind: 'cards', title: 'Implementation commitment', subtitle: 'A disciplined, prevention-first unit that adds practical value to CPS and students.', cols: 2, cards: ['STUDENT VALUE\nClear guidance, early reporting, downloadable campus information and transparent case references.', 'CPS VALUE\nBetter prevention reach, structured intake, reliable records, trend intelligence and controlled referrals.', 'INSTITUTIONAL VALUE\nA repeatable model with governance, cost controls, evidence and measurable outcomes.', 'NEXT STEP\nApprove the structure and begin the 90-day Pretoria West Pilot implementation cycle.'] },
];

export { BRAND };
