-- Migration history compatibility marker for the second recorded campus-scope hardening application.
-- The executable migration remains in its original authored migration file.
-- No SQL is intentionally executed here.
