-- Student Safety Mobility and consent-based campus radar.
-- The existing incident and GPS map systems remain authoritative.

create table if not exists public.safety_mobility_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  campus public.campus_location not null,
  mode text not null check (mode in ('in_transit', 'night_travel', 'find_my_phone')),
  status text not null default 'active' check (status in ('active', 'paused', 'completed', 'cancelled', 'alerted', 'expired')),
  transport_type text,
  vehicle_details text,
  destination_label text,
  expected_end_at timestamptz,
  share_scope text not null default 'trusted_circle' check (share_scope in ('private', 'trusted_circle', 'campus_security')),
  consent_at timestamptz not null default now(),
  last_location_at timestamptz,
  incident_id uuid references public.incidents(id) on delete set null,
  alert_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.safety_mobility_location_updates (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.safety_mobility_sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_meters double precision,
  heading_degrees double precision,
  speed_mps double precision,
  battery_percent numeric(5,2),
  readable_location text,
  recorded_at timestamptz not null default now()
);

create table if not exists public.safety_mobility_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.safety_mobility_sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('started', 'location', 'paused', 'resumed', 'alerted', 'completed', 'cancelled', 'expired')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.student_safety_presence (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  campus public.campus_location not null,
  visibility text not null default 'off' check (visibility in ('off', 'campus_approximate', 'campus_exact')),
  status_message text,
  latitude double precision,
  longitude double precision,
  accuracy_meters double precision,
  zone_label text,
  sharing_until timestamptz,
  exact_location_consent_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint student_safety_presence_coordinate_pair check (
    (latitude is null and longitude is null)
    or (latitude is not null and longitude is not null)
  )
);

create index if not exists safety_mobility_sessions_user_status_idx
  on public.safety_mobility_sessions(user_id, status, created_at desc);
create index if not exists safety_mobility_sessions_campus_alert_idx
  on public.safety_mobility_sessions(campus, status, last_location_at desc);
create index if not exists safety_mobility_updates_session_time_idx
  on public.safety_mobility_location_updates(session_id, recorded_at desc);
create index if not exists student_safety_presence_campus_seen_idx
  on public.student_safety_presence(campus, visibility, last_seen_at desc);

alter table public.safety_mobility_sessions enable row level security;
alter table public.safety_mobility_location_updates enable row level security;
alter table public.safety_mobility_events enable row level security;
alter table public.student_safety_presence enable row level security;

revoke all on public.safety_mobility_sessions from anon;
revoke all on public.safety_mobility_location_updates from anon;
revoke all on public.safety_mobility_events from anon;
revoke all on public.student_safety_presence from anon;

grant select on public.safety_mobility_sessions to authenticated;
grant select on public.safety_mobility_location_updates to authenticated;
grant select on public.safety_mobility_events to authenticated;
grant select on public.student_safety_presence to authenticated;

drop policy if exists safety_sessions_owner_read on public.safety_mobility_sessions;
create policy safety_sessions_owner_read on public.safety_mobility_sessions
for select to authenticated using (
  user_id = auth.uid()
  or public.has_role(auth.uid(), 'admin'::public.user_role)
  or (
    public.has_role(auth.uid(), 'security'::public.user_role)
    and (status = 'alerted' or share_scope = 'campus_security')
    and exists (
      select 1 from public.admin_access access
      where access.admin_id = auth.uid()
        and access.campus = safety_mobility_sessions.campus
    )
  )
);

drop policy if exists safety_updates_owner_read on public.safety_mobility_location_updates;
create policy safety_updates_owner_read on public.safety_mobility_location_updates
for select to authenticated using (
  user_id = auth.uid()
  or exists (
    select 1 from public.safety_mobility_sessions session
    where session.id = safety_mobility_location_updates.session_id
      and (
        public.has_role(auth.uid(), 'admin'::public.user_role)
        or (
          public.has_role(auth.uid(), 'security'::public.user_role)
          and (session.status = 'alerted' or session.share_scope = 'campus_security')
          and exists (
            select 1 from public.admin_access access
            where access.admin_id = auth.uid()
              and access.campus = session.campus
          )
        )
      )
  )
);

drop policy if exists safety_events_owner_read on public.safety_mobility_events;
create policy safety_events_owner_read on public.safety_mobility_events
for select to authenticated using (
  user_id = auth.uid()
  or public.has_role(auth.uid(), 'admin'::public.user_role)
  or exists (
    select 1 from public.safety_mobility_sessions session
    where session.id = safety_mobility_events.session_id
      and public.has_role(auth.uid(), 'security'::public.user_role)
      and (session.status = 'alerted' or session.share_scope = 'campus_security')
      and exists (
        select 1 from public.admin_access access
        where access.admin_id = auth.uid()
          and access.campus = session.campus
      )
  )
);

drop policy if exists safety_presence_owner_read on public.student_safety_presence;
create policy safety_presence_owner_read on public.student_safety_presence
for select to authenticated using (user_id = auth.uid());

create or replace function public.safety_start_mobility_session(
  p_mode text,
  p_campus public.campus_location,
  p_transport_type text default null,
  p_vehicle_details text default null,
  p_destination_label text default null,
  p_expected_end_at timestamptz default null,
  p_share_scope text default 'trusted_circle'
)
returns public.safety_mobility_sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.safety_mobility_sessions;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_mode not in ('in_transit', 'night_travel', 'find_my_phone') then raise exception 'Unsupported mobility mode'; end if;
  if p_share_scope not in ('private', 'trusted_circle', 'campus_security') then raise exception 'Unsupported sharing scope'; end if;
  if p_expected_end_at is not null and p_expected_end_at <= now() then raise exception 'Expected end time must be in the future'; end if;

  update public.safety_mobility_sessions
  set status = 'completed', ended_at = now(), updated_at = now()
  where user_id = auth.uid() and status in ('active', 'paused');

  insert into public.safety_mobility_sessions (
    user_id, campus, mode, transport_type, vehicle_details,
    destination_label, expected_end_at, share_scope
  ) values (
    auth.uid(), p_campus, p_mode, nullif(btrim(p_transport_type), ''),
    nullif(btrim(p_vehicle_details), ''), nullif(btrim(p_destination_label), ''),
    p_expected_end_at, p_share_scope
  ) returning * into session_row;

  insert into public.safety_mobility_events(session_id, user_id, event_type, details)
  values (session_row.id, auth.uid(), 'started', jsonb_build_object('mode', p_mode, 'share_scope', p_share_scope));

  return session_row;
end;
$$;

create or replace function public.safety_update_mobility_location(
  p_session_id uuid,
  p_latitude double precision,
  p_longitude double precision,
  p_accuracy_meters double precision default null,
  p_heading_degrees double precision default null,
  p_speed_mps double precision default null,
  p_battery_percent numeric default null,
  p_readable_location text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.safety_mobility_sessions;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then raise exception 'Invalid coordinates'; end if;

  select * into session_row
  from public.safety_mobility_sessions
  where id = p_session_id and user_id = auth.uid() and status in ('active', 'paused', 'alerted')
  for update;
  if not found then raise exception 'Active mobility session not found'; end if;

  insert into public.safety_mobility_location_updates (
    session_id, user_id, latitude, longitude, accuracy_meters,
    heading_degrees, speed_mps, battery_percent, readable_location
  ) values (
    session_row.id, auth.uid(), p_latitude, p_longitude, p_accuracy_meters,
    p_heading_degrees, p_speed_mps, p_battery_percent, nullif(btrim(p_readable_location), '')
  );

  update public.safety_mobility_sessions
  set last_location_at = now(), updated_at = now()
  where id = session_row.id;

  update public.student_safety_presence
  set latitude = p_latitude,
      longitude = p_longitude,
      accuracy_meters = p_accuracy_meters,
      zone_label = coalesce(nullif(btrim(p_readable_location), ''), zone_label),
      last_seen_at = now(),
      updated_at = now()
  where user_id = auth.uid()
    and visibility <> 'off'
    and (sharing_until is null or sharing_until > now());

  if session_row.incident_id is not null then
    insert into public.incident_location_updates (
      incident_id, location_lat, location_lng, location_address, accuracy_meters
    ) values (
      session_row.incident_id, p_latitude, p_longitude,
      coalesce(nullif(btrim(p_readable_location), ''), 'Live safety location'), p_accuracy_meters
    );

    update public.incidents
    set location_lat = p_latitude,
        location_lng = p_longitude,
        location_description = coalesce(nullif(btrim(p_readable_location), ''), 'Live safety location'),
        updated_at = now()
    where id = session_row.incident_id;
  end if;
end;
$$;

create or replace function public.safety_end_mobility_session(
  p_session_id uuid,
  p_status text default 'completed'
)
returns public.safety_mobility_sessions
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.safety_mobility_sessions;
  event_name text;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_status not in ('completed', 'cancelled') then raise exception 'Unsupported completion status'; end if;
  event_name := p_status;

  update public.safety_mobility_sessions
  set status = p_status, ended_at = now(), updated_at = now()
  where id = p_session_id and user_id = auth.uid()
  returning * into session_row;
  if not found then raise exception 'Mobility session not found'; end if;

  insert into public.safety_mobility_events(session_id, user_id, event_type)
  values (session_row.id, auth.uid(), event_name);
  return session_row;
end;
$$;

create or replace function public.safety_trigger_mobility_alert(
  p_session_id uuid,
  p_reason text default 'Student reported feeling unsafe while travelling'
)
returns table(session_id uuid, incident_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.safety_mobility_sessions;
  latest_location public.safety_mobility_location_updates;
  created_incident uuid;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  select * into session_row
  from public.safety_mobility_sessions
  where id = p_session_id and user_id = auth.uid()
  for update;
  if not found then raise exception 'Mobility session not found'; end if;

  if session_row.incident_id is not null then
    return query select session_row.id, session_row.incident_id;
    return;
  end if;

  select * into latest_location
  from public.safety_mobility_location_updates
  where safety_mobility_location_updates.session_id = session_row.id
  order by recorded_at desc limit 1;

  insert into public.incidents (
    title, description, category, status, is_anonymous,
    location_lat, location_lng, location_description,
    reporter_id, submitted_by, campus
  ) values (
    case session_row.mode
      when 'in_transit' then 'In-transit safety alert'
      when 'night_travel' then 'Night-travel safety alert'
      else 'Device-location safety alert'
    end,
    concat_ws(E'\n',
      coalesce(nullif(btrim(p_reason), ''), 'Student reported feeling unsafe.'),
      'Mode: ' || replace(session_row.mode, '_', ' '),
      case when session_row.transport_type is not null then 'Transport: ' || session_row.transport_type end,
      case when session_row.vehicle_details is not null then 'Vehicle/details: ' || session_row.vehicle_details end,
      case when session_row.destination_label is not null then 'Destination: ' || session_row.destination_label end,
      'Generated from My CCSF Safety Mobility.'
    ),
    'Public violence'::public.incident_category,
    'pending'::public.incident_status,
    false,
    latest_location.latitude,
    latest_location.longitude,
    coalesce(latest_location.readable_location, 'Latest live safety location'),
    auth.uid(), auth.uid(), session_row.campus
  ) returning id into created_incident;

  if latest_location.id is not null then
    insert into public.incident_location_updates (
      incident_id, location_lat, location_lng, location_address, accuracy_meters
    ) values (
      created_incident, latest_location.latitude, latest_location.longitude,
      coalesce(latest_location.readable_location, 'Latest live safety location'), latest_location.accuracy_meters
    );
  end if;

  update public.safety_mobility_sessions
  set status = 'alerted', share_scope = 'campus_security', incident_id = created_incident,
      alert_reason = coalesce(nullif(btrim(p_reason), ''), 'Student reported feeling unsafe.'), updated_at = now()
  where id = session_row.id;

  insert into public.safety_mobility_events(session_id, user_id, event_type, details)
  values (session_row.id, auth.uid(), 'alerted', jsonb_build_object('incident_id', created_incident, 'reason', p_reason));

  return query select session_row.id, created_incident;
end;
$$;

create or replace function public.safety_set_student_presence(
  p_campus public.campus_location,
  p_visibility text,
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_accuracy_meters double precision default null,
  p_zone_label text default null,
  p_status_message text default null,
  p_sharing_until timestamptz default null,
  p_confirm_exact boolean default false
)
returns public.student_safety_presence
language plpgsql
security definer
set search_path = public
as $$
declare
  presence_row public.student_safety_presence;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_visibility not in ('off', 'campus_approximate', 'campus_exact') then raise exception 'Unsupported visibility'; end if;
  if p_visibility = 'campus_exact' and not p_confirm_exact then raise exception 'Exact-location consent is required'; end if;
  if (p_latitude is null) <> (p_longitude is null) then raise exception 'Latitude and longitude must be supplied together'; end if;

  insert into public.student_safety_presence (
    user_id, campus, visibility, latitude, longitude, accuracy_meters,
    zone_label, status_message, sharing_until, exact_location_consent_at, last_seen_at
  ) values (
    auth.uid(), p_campus, p_visibility, p_latitude, p_longitude, p_accuracy_meters,
    nullif(btrim(p_zone_label), ''), nullif(btrim(p_status_message), ''), p_sharing_until,
    case when p_visibility = 'campus_exact' then now() else null end,
    case when p_visibility = 'off' then null else now() end
  )
  on conflict (user_id) do update set
    campus = excluded.campus,
    visibility = excluded.visibility,
    latitude = case when excluded.visibility = 'off' then null else excluded.latitude end,
    longitude = case when excluded.visibility = 'off' then null else excluded.longitude end,
    accuracy_meters = case when excluded.visibility = 'off' then null else excluded.accuracy_meters end,
    zone_label = excluded.zone_label,
    status_message = excluded.status_message,
    sharing_until = excluded.sharing_until,
    exact_location_consent_at = case when excluded.visibility = 'campus_exact' then now() else null end,
    last_seen_at = case when excluded.visibility = 'off' then null else now() end,
    updated_at = now()
  returning * into presence_row;

  return presence_row;
end;
$$;

create or replace function public.safety_list_campus_radar(p_campus public.campus_location)
returns table (
  user_id uuid,
  full_name text,
  avatar_url text,
  campus public.campus_location,
  visibility text,
  status_message text,
  latitude double precision,
  longitude double precision,
  accuracy_meters double precision,
  zone_label text,
  last_seen_at timestamptz,
  is_exact boolean
)
language sql
security definer
stable
set search_path = public
as $$
  select
    presence.user_id,
    coalesce(profile.full_name, concat_ws(' ', profile.first_name, profile.last_name), 'TUT Student') as full_name,
    profile.avatar_url,
    presence.campus,
    presence.visibility,
    presence.status_message,
    case when presence.user_id = auth.uid() or presence.visibility = 'campus_exact'
      then presence.latitude else round(presence.latitude::numeric, 3)::double precision end as latitude,
    case when presence.user_id = auth.uid() or presence.visibility = 'campus_exact'
      then presence.longitude else round(presence.longitude::numeric, 3)::double precision end as longitude,
    case when presence.user_id = auth.uid() or presence.visibility = 'campus_exact'
      then presence.accuracy_meters else greatest(coalesce(presence.accuracy_meters, 0), 120) end as accuracy_meters,
    presence.zone_label,
    presence.last_seen_at,
    (presence.user_id = auth.uid() or presence.visibility = 'campus_exact') as is_exact
  from public.student_safety_presence presence
  join public.profiles profile on profile.id = presence.user_id
  where auth.uid() is not null
    and presence.campus = p_campus
    and presence.visibility <> 'off'
    and presence.latitude is not null
    and presence.longitude is not null
    and presence.last_seen_at > now() - interval '15 minutes'
    and (presence.sharing_until is null or presence.sharing_until > now())
  order by (presence.user_id = auth.uid()) desc, presence.last_seen_at desc
  limit 60;
$$;

grant execute on function public.safety_start_mobility_session(text, public.campus_location, text, text, text, timestamptz, text) to authenticated;
grant execute on function public.safety_update_mobility_location(uuid, double precision, double precision, double precision, double precision, double precision, numeric, text) to authenticated;
grant execute on function public.safety_end_mobility_session(uuid, text) to authenticated;
grant execute on function public.safety_trigger_mobility_alert(uuid, text) to authenticated;
grant execute on function public.safety_set_student_presence(public.campus_location, text, double precision, double precision, double precision, text, text, timestamptz, boolean) to authenticated;
grant execute on function public.safety_list_campus_radar(public.campus_location) to authenticated;

-- Realtime is optional; ignore duplicate publication membership.
do $$ begin
  alter publication supabase_realtime add table public.safety_mobility_sessions;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.student_safety_presence;
exception when duplicate_object then null; end $$;
