-- CCSF Traffic department: visitor parking, student permits, gate events,
-- road-safety notices and configurable physical-permit templates.

create type public.traffic_pass_status as enum (
  'pending',
  'approved',
  'rejected',
  'checked_in',
  'checked_out',
  'expired',
  'cancelled'
);

create type public.traffic_student_permit_status as enum (
  'pending',
  'active',
  'suspended',
  'expired',
  'rejected'
);

create type public.traffic_template_status as enum ('draft', 'active', 'archived');
create type public.traffic_permit_kind as enum ('student', 'visitor');

create table public.traffic_visitor_passes (
  id uuid primary key default gen_random_uuid(),
  reference_code text not null unique,
  tracking_token_hash text not null,
  contact_fingerprint text not null,
  visitor_name text not null check (char_length(visitor_name) between 2 and 120),
  visitor_email text,
  visitor_phone text not null check (char_length(visitor_phone) between 7 and 24),
  vehicle_registration text not null check (char_length(vehicle_registration) between 2 and 20),
  vehicle_make text,
  vehicle_colour text,
  campus public.campus_location not null,
  host_name text not null check (char_length(host_name) between 2 and 120),
  host_department text,
  visit_purpose text not null check (char_length(visit_purpose) between 3 and 500),
  visit_date date not null,
  expected_arrival time not null,
  status public.traffic_pass_status not null default 'pending',
  decision_notes text,
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  checked_in_at timestamptz,
  checked_out_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.traffic_student_permits (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null unique references public.profiles(id) on delete cascade,
  campus public.campus_location not null,
  vehicle_registration text not null check (char_length(vehicle_registration) between 2 and 20),
  vehicle_make text,
  vehicle_colour text,
  permit_number text unique,
  status public.traffic_student_permit_status not null default 'pending',
  valid_from date,
  valid_until date,
  decision_notes text,
  issued_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint traffic_student_permit_dates check (
    valid_from is null or valid_until is null or valid_until >= valid_from
  )
);

create table public.traffic_permit_templates (
  id uuid primary key default gen_random_uuid(),
  campus public.campus_location,
  permit_kind public.traffic_permit_kind not null,
  name text not null check (char_length(name) between 2 and 100),
  storage_path text not null unique,
  status public.traffic_template_status not null default 'draft',
  notes text,
  created_by uuid not null references public.profiles(id) on delete restrict,
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.traffic_gate_events (
  id bigint generated by default as identity primary key,
  visitor_pass_id uuid not null references public.traffic_visitor_passes(id) on delete cascade,
  event_type public.traffic_pass_status not null,
  gate_name text,
  notes text,
  recorded_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.traffic_road_safety_notices (
  id uuid primary key default gen_random_uuid(),
  campus public.campus_location,
  title text not null check (char_length(title) between 3 and 120),
  summary text not null check (char_length(summary) between 3 and 300),
  severity text not null default 'information' check (severity in ('information', 'caution', 'urgent')),
  is_published boolean not null default false,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint traffic_notice_dates check (ends_at is null or ends_at > starts_at)
);

create index traffic_visitor_passes_campus_status_date_idx
  on public.traffic_visitor_passes(campus, status, visit_date, expected_arrival);
create index traffic_visitor_passes_contact_rate_idx
  on public.traffic_visitor_passes(contact_fingerprint, created_at desc);
create index traffic_student_permits_campus_status_idx
  on public.traffic_student_permits(campus, status, updated_at desc);
create index traffic_gate_events_pass_time_idx
  on public.traffic_gate_events(visitor_pass_id, created_at desc);
create index traffic_notices_published_time_idx
  on public.traffic_road_safety_notices(is_published, starts_at desc, ends_at);

create trigger traffic_visitor_passes_updated_at
before update on public.traffic_visitor_passes
for each row execute function public.handle_updated_at();
create trigger traffic_student_permits_updated_at
before update on public.traffic_student_permits
for each row execute function public.handle_updated_at();
create trigger traffic_permit_templates_updated_at
before update on public.traffic_permit_templates
for each row execute function public.handle_updated_at();
create trigger traffic_road_safety_notices_updated_at
before update on public.traffic_road_safety_notices
for each row execute function public.handle_updated_at();

alter table public.traffic_visitor_passes enable row level security;
alter table public.traffic_student_permits enable row level security;
alter table public.traffic_permit_templates enable row level security;
alter table public.traffic_gate_events enable row level security;
alter table public.traffic_road_safety_notices enable row level security;

revoke all on public.traffic_visitor_passes from anon, authenticated;
revoke all on public.traffic_student_permits from anon, authenticated;
revoke all on public.traffic_permit_templates from anon, authenticated;
revoke all on public.traffic_gate_events from anon, authenticated;
revoke all on public.traffic_road_safety_notices from anon, authenticated;

grant select (
  id, reference_code, visitor_name, visitor_email, visitor_phone,
  vehicle_registration, vehicle_make, vehicle_colour, campus,
  host_name, host_department, visit_purpose, visit_date, expected_arrival,
  status, decision_notes, approved_by, approved_at,
  checked_in_at, checked_out_at, created_at, updated_at
) on public.traffic_visitor_passes to authenticated;
grant select on public.traffic_student_permits to authenticated;
grant select, insert, update, delete on public.traffic_permit_templates to authenticated;
grant select on public.traffic_gate_events to authenticated;
grant select on public.traffic_road_safety_notices to anon, authenticated;
grant insert, update, delete on public.traffic_road_safety_notices to authenticated;

create policy traffic_staff_read_visitor_passes
on public.traffic_visitor_passes for select to authenticated
using (
  public.has_role((select auth.uid()), 'admin'::public.user_role)
  or (
    public.has_role((select auth.uid()), 'security'::public.user_role)
    and public.has_campus_access((select auth.uid()), campus)
  )
);

create policy traffic_student_read_own_permit
on public.traffic_student_permits for select to authenticated
using (
  student_id = (select auth.uid())
  or public.has_role((select auth.uid()), 'admin'::public.user_role)
  or (
    public.has_role((select auth.uid()), 'security'::public.user_role)
    and public.has_campus_access((select auth.uid()), campus)
  )
);

create policy traffic_staff_read_templates
on public.traffic_permit_templates for select to authenticated
using (
  public.has_role((select auth.uid()), 'admin'::public.user_role)
  or public.has_role((select auth.uid()), 'security'::public.user_role)
);

create policy traffic_staff_insert_templates
on public.traffic_permit_templates for insert to authenticated
with check (
  created_by = (select auth.uid())
  and (
    public.has_role((select auth.uid()), 'admin'::public.user_role)
    or (
      public.has_role((select auth.uid()), 'security'::public.user_role)
      and campus is not null
      and public.has_campus_access((select auth.uid()), campus)
    )
  )
);

create policy traffic_staff_update_templates
on public.traffic_permit_templates for update to authenticated
using (
  public.has_role((select auth.uid()), 'admin'::public.user_role)
  or (
    public.has_role((select auth.uid()), 'security'::public.user_role)
    and campus is not null
    and public.has_campus_access((select auth.uid()), campus)
  )
)
with check (
  public.has_role((select auth.uid()), 'admin'::public.user_role)
  or (
    public.has_role((select auth.uid()), 'security'::public.user_role)
    and campus is not null
    and public.has_campus_access((select auth.uid()), campus)
  )
);

create policy traffic_admin_delete_templates
on public.traffic_permit_templates for delete to authenticated
using (public.has_role((select auth.uid()), 'admin'::public.user_role));

create policy traffic_staff_read_gate_events
on public.traffic_gate_events for select to authenticated
using (
  exists (
    select 1 from public.traffic_visitor_passes pass
    where pass.id = traffic_gate_events.visitor_pass_id
      and (
        public.has_role((select auth.uid()), 'admin'::public.user_role)
        or (
          public.has_role((select auth.uid()), 'security'::public.user_role)
          and public.has_campus_access((select auth.uid()), pass.campus)
        )
      )
  )
);

create policy traffic_public_read_published_notices
on public.traffic_road_safety_notices for select to anon, authenticated
using (
  is_published
  and starts_at <= now()
  and (ends_at is null or ends_at > now())
);

create policy traffic_staff_read_all_notices
on public.traffic_road_safety_notices for select to authenticated
using (
  public.has_role((select auth.uid()), 'admin'::public.user_role)
  or (
    public.has_role((select auth.uid()), 'security'::public.user_role)
    and (campus is null or public.has_campus_access((select auth.uid()), campus))
  )
);

create policy traffic_staff_insert_notices
on public.traffic_road_safety_notices for insert to authenticated
with check (
  created_by = (select auth.uid())
  and (
    public.has_role((select auth.uid()), 'admin'::public.user_role)
    or (
      public.has_role((select auth.uid()), 'security'::public.user_role)
      and campus is not null
      and public.has_campus_access((select auth.uid()), campus)
    )
  )
);

create policy traffic_staff_update_notices
on public.traffic_road_safety_notices for update to authenticated
using (
  public.has_role((select auth.uid()), 'admin'::public.user_role)
  or (
    public.has_role((select auth.uid()), 'security'::public.user_role)
    and campus is not null
    and public.has_campus_access((select auth.uid()), campus)
  )
)
with check (
  public.has_role((select auth.uid()), 'admin'::public.user_role)
  or (
    public.has_role((select auth.uid()), 'security'::public.user_role)
    and campus is not null
    and public.has_campus_access((select auth.uid()), campus)
  )
);

create policy traffic_admin_delete_notices
on public.traffic_road_safety_notices for delete to authenticated
using (public.has_role((select auth.uid()), 'admin'::public.user_role));

create or replace function public.traffic_create_visitor_pass(
  p_visitor_name text,
  p_visitor_email text,
  p_visitor_phone text,
  p_vehicle_registration text,
  p_vehicle_make text,
  p_vehicle_colour text,
  p_campus public.campus_location,
  p_host_name text,
  p_host_department text,
  p_visit_purpose text,
  p_visit_date date,
  p_expected_arrival time
)
returns table (
  pass_id uuid,
  reference_code text,
  tracking_token text,
  pass_status public.traffic_pass_status,
  submitted_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_name text := nullif(btrim(p_visitor_name), '');
  v_email text := nullif(lower(btrim(p_visitor_email)), '');
  v_phone text := regexp_replace(coalesce(p_visitor_phone, ''), '[^0-9+]', '', 'g');
  v_registration text := upper(regexp_replace(coalesce(p_vehicle_registration, ''), '\s+', ' ', 'g'));
  v_reference text;
  v_token text := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
  v_fingerprint text;
  v_row public.traffic_visitor_passes;
begin
  if v_name is null or char_length(v_name) not between 2 and 120 then
    raise exception 'Enter the visitor full name';
  end if;
  if v_email is not null and (char_length(v_email) > 160 or v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$') then
    raise exception 'Enter a valid email address';
  end if;
  if char_length(v_phone) not between 7 and 24 then
    raise exception 'Enter a valid phone number';
  end if;
  if char_length(v_registration) not between 2 and 20 then
    raise exception 'Enter a valid vehicle registration';
  end if;
  if char_length(coalesce(p_host_name, '')) not between 2 and 120 then
    raise exception 'Enter the host name';
  end if;
  if char_length(coalesce(p_visit_purpose, '')) not between 3 and 500 then
    raise exception 'Describe the purpose of the visit';
  end if;
  if p_visit_date < current_date or p_visit_date > current_date + 120 then
    raise exception 'Visit date must be within the next 120 days';
  end if;

  v_fingerprint := encode(digest(coalesce(v_email, '') || '|' || v_phone, 'sha256'), 'hex');
  if (
    select count(*)
    from public.traffic_visitor_passes
    where contact_fingerprint = v_fingerprint
      and created_at > now() - interval '1 hour'
  ) >= 3 then
    raise exception 'Too many recent parking requests. Try again later or contact the Traffic department.';
  end if;

  if exists (
    select 1 from public.traffic_visitor_passes
    where visit_date = p_visit_date
      and campus = p_campus
      and vehicle_registration = v_registration
      and status not in ('rejected', 'cancelled', 'expired')
  ) then
    raise exception 'A parking request already exists for this vehicle, campus and date';
  end if;

  v_reference := 'VIS-' || to_char(p_visit_date, 'YYMMDD') || '-' ||
    upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));

  insert into public.traffic_visitor_passes (
    reference_code, tracking_token_hash, contact_fingerprint,
    visitor_name, visitor_email, visitor_phone,
    vehicle_registration, vehicle_make, vehicle_colour,
    campus, host_name, host_department, visit_purpose,
    visit_date, expected_arrival
  ) values (
    v_reference, encode(digest(v_token, 'sha256'), 'hex'), v_fingerprint,
    v_name, v_email, v_phone,
    v_registration, nullif(btrim(p_vehicle_make), ''), nullif(btrim(p_vehicle_colour), ''),
    p_campus, btrim(p_host_name), nullif(btrim(p_host_department), ''), btrim(p_visit_purpose),
    p_visit_date, p_expected_arrival
  ) returning * into v_row;

  return query select v_row.id, v_row.reference_code, v_token, v_row.status, v_row.created_at;
end;
$$;

create or replace function public.traffic_track_visitor_pass(
  p_reference_code text,
  p_tracking_token text
)
returns table (
  pass_id uuid,
  reference_code text,
  visitor_name text,
  vehicle_registration text,
  campus public.campus_location,
  visit_date date,
  expected_arrival time,
  pass_status public.traffic_pass_status,
  decision_notes text,
  approved_at timestamptz,
  checked_in_at timestamptz,
  checked_out_at timestamptz,
  submitted_at timestamptz
)
language sql
security definer
stable
set search_path = public, extensions
as $$
  select
    pass.id,
    pass.reference_code,
    pass.visitor_name,
    pass.vehicle_registration,
    pass.campus,
    pass.visit_date,
    pass.expected_arrival,
    pass.status,
    pass.decision_notes,
    pass.approved_at,
    pass.checked_in_at,
    pass.checked_out_at,
    pass.created_at
  from public.traffic_visitor_passes pass
  where pass.reference_code = upper(btrim(p_reference_code))
    and pass.tracking_token_hash = encode(digest(coalesce(p_tracking_token, ''), 'sha256'), 'hex')
  limit 1
$$;

create or replace function public.traffic_request_student_permit(
  p_campus public.campus_location,
  p_vehicle_registration text,
  p_vehicle_make text,
  p_vehicle_colour text
)
returns public.traffic_student_permits
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_profile public.profiles;
  v_registration text := upper(regexp_replace(coalesce(p_vehicle_registration, ''), '\s+', ' ', 'g'));
  v_existing public.traffic_student_permits;
  v_row public.traffic_student_permits;
begin
  if auth.uid() is null or not public.has_role(auth.uid(), 'student'::public.user_role) then
    raise exception 'Student authentication is required';
  end if;
  select * into v_profile from public.profiles where id = auth.uid();
  if v_profile.campus is null or v_profile.campus <> p_campus then
    raise exception 'The permit campus must match the verified student profile';
  end if;
  if char_length(v_registration) not between 2 and 20 then
    raise exception 'Enter a valid vehicle registration';
  end if;

  select * into v_existing
  from public.traffic_student_permits
  where student_id = auth.uid()
  for update;

  if found and v_existing.status in ('active', 'suspended') then
    raise exception 'An issued permit must be changed by the Traffic department';
  end if;

  insert into public.traffic_student_permits (
    student_id, campus, vehicle_registration, vehicle_make, vehicle_colour, status
  ) values (
    auth.uid(), p_campus, v_registration,
    nullif(btrim(p_vehicle_make), ''), nullif(btrim(p_vehicle_colour), ''), 'pending'
  )
  on conflict (student_id) do update set
    campus = excluded.campus,
    vehicle_registration = excluded.vehicle_registration,
    vehicle_make = excluded.vehicle_make,
    vehicle_colour = excluded.vehicle_colour,
    status = 'pending',
    decision_notes = null,
    updated_at = now()
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.traffic_update_visitor_pass_status(
  p_pass_id uuid,
  p_status public.traffic_pass_status,
  p_gate_name text default null,
  p_notes text default null
)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_pass public.traffic_visitor_passes;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  select * into v_pass
  from public.traffic_visitor_passes
  where id = p_pass_id
  for update;
  if not found then raise exception 'Visitor pass not found'; end if;

  if not (
    public.has_role(auth.uid(), 'admin'::public.user_role)
    or (
      public.has_role(auth.uid(), 'security'::public.user_role)
      and public.has_campus_access(auth.uid(), v_pass.campus)
    )
  ) then
    raise exception 'Not authorised for this campus';
  end if;

  if not (
    (v_pass.status = 'pending' and p_status in ('approved', 'rejected', 'cancelled'))
    or (v_pass.status = 'approved' and p_status in ('checked_in', 'cancelled', 'expired'))
    or (v_pass.status = 'checked_in' and p_status in ('checked_out', 'cancelled'))
    or (v_pass.status = p_status)
  ) then
    raise exception 'Unsupported visitor pass status transition';
  end if;

  update public.traffic_visitor_passes set
    status = p_status,
    decision_notes = case when p_notes is null then decision_notes else nullif(btrim(p_notes), '') end,
    approved_by = case when p_status = 'approved' then auth.uid() else approved_by end,
    approved_at = case when p_status = 'approved' then coalesce(approved_at, now()) else approved_at end,
    checked_in_at = case when p_status = 'checked_in' then coalesce(checked_in_at, now()) else checked_in_at end,
    checked_out_at = case when p_status = 'checked_out' then coalesce(checked_out_at, now()) else checked_out_at end,
    updated_at = now()
  where id = p_pass_id;

  insert into public.traffic_gate_events (
    visitor_pass_id, event_type, gate_name, notes, recorded_by
  ) values (
    p_pass_id, p_status, nullif(btrim(p_gate_name), ''), nullif(btrim(p_notes), ''), auth.uid()
  );
end;
$$;

create or replace function public.traffic_update_student_permit_status(
  p_permit_id uuid,
  p_status public.traffic_student_permit_status,
  p_notes text default null,
  p_valid_until date default null
)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_permit public.traffic_student_permits;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  select * into v_permit
  from public.traffic_student_permits
  where id = p_permit_id
  for update;
  if not found then raise exception 'Student permit not found'; end if;

  if not (
    public.has_role(auth.uid(), 'admin'::public.user_role)
    or (
      public.has_role(auth.uid(), 'security'::public.user_role)
      and public.has_campus_access(auth.uid(), v_permit.campus)
    )
  ) then
    raise exception 'Not authorised for this campus';
  end if;

  if p_status not in ('active', 'suspended', 'expired', 'rejected') then
    raise exception 'Unsupported student permit status';
  end if;

  update public.traffic_student_permits set
    status = p_status,
    decision_notes = nullif(btrim(p_notes), ''),
    permit_number = case
      when p_status = 'active' then coalesce(
        permit_number,
        'STU-' || upper(substr(replace(v_permit.campus::text, '_', ''), 1, 4)) ||
          '-' || to_char(current_date, 'YY') || '-' ||
          upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))
      )
      else permit_number
    end,
    valid_from = case when p_status = 'active' then coalesce(valid_from, current_date) else valid_from end,
    valid_until = case
      when p_status = 'active' then coalesce(p_valid_until, valid_until, current_date + 365)
      else valid_until
    end,
    issued_by = case when p_status = 'active' then auth.uid() else issued_by end,
    updated_at = now()
  where id = p_permit_id;
end;
$$;

revoke all on function public.traffic_create_visitor_pass(
  text, text, text, text, text, text, public.campus_location,
  text, text, text, date, time
) from public;
revoke all on function public.traffic_track_visitor_pass(text, text) from public;
revoke all on function public.traffic_request_student_permit(
  public.campus_location, text, text, text
) from public;
revoke all on function public.traffic_update_visitor_pass_status(
  uuid, public.traffic_pass_status, text, text
) from public;

grant execute on function public.traffic_create_visitor_pass(
  text, text, text, text, text, text, public.campus_location,
  text, text, text, date, time
) to anon, authenticated;
grant execute on function public.traffic_track_visitor_pass(text, text) to anon, authenticated;
grant execute on function public.traffic_request_student_permit(
  public.campus_location, text, text, text
) to authenticated;
grant execute on function public.traffic_update_visitor_pass_status(
  uuid, public.traffic_pass_status, text, text
) to authenticated;

revoke all on function public.traffic_update_student_permit_status(
  uuid, public.traffic_student_permit_status, text, date
) from public;
grant execute on function public.traffic_update_student_permit_status(
  uuid, public.traffic_student_permit_status, text, date
) to authenticated;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'traffic-permit-templates',
  'traffic-permit-templates',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy traffic_staff_read_template_files
on storage.objects for select to authenticated
using (
  bucket_id = 'traffic-permit-templates'
  and (
    public.has_role((select auth.uid()), 'admin'::public.user_role)
    or public.has_role((select auth.uid()), 'security'::public.user_role)
  )
);

create policy traffic_staff_upload_template_files
on storage.objects for insert to authenticated
with check (
  bucket_id = 'traffic-permit-templates'
  and (storage.foldername(name))[2] = (select auth.uid())::text
  and (
    public.has_role((select auth.uid()), 'admin'::public.user_role)
    or public.has_role((select auth.uid()), 'security'::public.user_role)
  )
);

create policy traffic_staff_update_own_template_files
on storage.objects for update to authenticated
using (
  bucket_id = 'traffic-permit-templates'
  and owner_id = (select auth.uid())::text
)
with check (
  bucket_id = 'traffic-permit-templates'
  and owner_id = (select auth.uid())::text
);

create policy traffic_staff_delete_own_template_files
on storage.objects for delete to authenticated
using (
  bucket_id = 'traffic-permit-templates'
  and (
    owner_id = (select auth.uid())::text
    or public.has_role((select auth.uid()), 'admin'::public.user_role)
  )
);

insert into public.traffic_road_safety_notices (
  id, campus, title, summary, severity, is_published, starts_at
) values
  (
    'f1000000-0000-4000-8000-000000000001',
    null,
    'Drive at walking speed near pedestrians',
    'Campus roads are shared spaces. Slow down at crossings, residences, lecture venues and gate queues.',
    'caution',
    true,
    now()
  ),
  (
    'f1000000-0000-4000-8000-000000000002',
    null,
    'Display only an approved parking permit',
    'A submitted request is not permission to enter. Wait for approval and follow Traffic or CPS instructions at the gate.',
    'information',
    true,
    now()
  ),
  (
    'f1000000-0000-4000-8000-000000000003',
    null,
    'Students must use student parking zones',
    'Student vehicles may park only in marked student bays. Staff, visitor, accessible and emergency bays remain restricted.',
    'information',
    true,
    now()
  )
on conflict (id) do update set
  title = excluded.title,
  summary = excluded.summary,
  severity = excluded.severity,
  is_published = excluded.is_published;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'traffic_student_permits'
  ) then
    alter publication supabase_realtime add table public.traffic_student_permits;
  end if;
end;
$$;
