alter table public.pilot_programs alter column created_by set default auth.uid();
alter table public.pilot_scenarios alter column created_by set default auth.uid();
alter table public.pilot_participants alter column invited_by set default auth.uid();
alter table public.pilot_sessions alter column user_id set default auth.uid();
alter table public.pilot_reports alter column submitted_by set default auth.uid();
alter table public.pilot_reports alter column reference_number set default '';
alter table public.pilot_attachments alter column uploaded_by set default auth.uid();
alter table public.pilot_feature_tests alter column user_id set default auth.uid();
alter table public.pilot_feedback alter column user_id set default auth.uid();
alter table public.pilot_programs enable row level security;
alter table public.pilot_scenarios enable row level security;
alter table public.pilot_participants enable row level security;
alter table public.pilot_sessions enable row level security;
alter table public.pilot_reports enable row level security;
alter table public.pilot_report_events enable row level security;
alter table public.pilot_location_events enable row level security;
alter table public.pilot_attachments enable row level security;
alter table public.pilot_notifications enable row level security;
alter table public.pilot_feature_tests enable row level security;
alter table public.pilot_feedback enable row level security;
alter table public.pilot_audit_logs enable row level security;